version: '3'

services:
  server:
    build: .
    image: growwserver:v1
    ports: 
      - 4000:4000
    volumes: 
      - .:/usr/src/app
    restart: on-failure
    command: npm run debug
    environment:
      - DBURI='mongodb://root:example@mongo:27017/ExternDB?authSource=admin&w=1'
      - HOST=0.0.0.0
  
  mongo:
    image: mongo:4.4.3
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: ExternDB
    ports: 
      - 27017:27017
    volumes:
      - ./data:/data/db

  mongo-express:
    image: mongo-express:0.54.0
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
